# Generated by Django 3.1.3 on 2020-11-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_lst',
            name='phone_num',
            field=models.IntegerField(blank=True),
        ),
    ]
