# Generated by Django 3.1.3 on 2020-11-23 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0004_auto_20201120_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=70, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_lst',
            name='phone_num',
            field=models.IntegerField(unique=True),
        ),
    ]
