# Generated by Django 3.1.3 on 2020-11-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0005_auto_20201123_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_lst',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
